# Generated by Django 2.0.2 on 2018-10-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False, verbose_name='Название спектакля')),
                ('photo', models.ImageField(upload_to='')),
                ('dateTime', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='PerfType',
            fields=[
                ('perfType', models.TextField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Тип спектакля')),
            ],
            options={
                'verbose_name': 'Тип спектакля',
                'verbose_name_plural': 'Типы спектаклей',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('sceneType', models.TextField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Тип сцены')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='perfType',
            field=models.ForeignKey(on_delete=None, to='performances.PerfType', verbose_name='Тип спектакля'),
        ),
        migrations.AddField(
            model_name='performance',
            name='scene',
            field=models.ForeignKey(on_delete=None, to='performances.Scene', verbose_name='Сцена'),
        ),
    ]
