# Generated by Django 2.0.2 on 2018-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.TextField(max_length=200, primary_key=True, serialize=False, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
