# Generated by Django 2.0.2 on 2018-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('first_field', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Картинка для карусели',
                'verbose_name_plural': 'Картинки для карусели',
            },
        ),
    ]
