# Generated by Django 2.0.2 on 2018-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselleimage',
            old_name='first_field',
            new_name='firstField',
        ),
    ]
