# Generated by Django 2.0.2 on 2018-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181005_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselleimage',
            name='firstField',
            field=models.BooleanField(default=False, verbose_name='Картинка будет отображаться первой'),
        ),
    ]
